source: app
destination: app/_site

# Site settings
title: BrandonSilver.com
subtitle: The website and blog of Brandon Silver, software developer.
description: > # this means to ignore newlines until the next configuration directive.
  A web-based log (``blog'') of the projects and studies of Brandon Silver.
author: Brandon Silver
#author_website: https://www.brandonsilver.com
email: brandon@brandonsilver.com

baseurl: "" # the subpath of your site, e.g. /blog. For deploying to github pages, this should match your repo name
url: "https://www.brandonsilver.com" # the base hostname & protocol for your site

twitter_username: 'alinuxuser'
github_username:  brandonsilver
disqus_shortname: brandonsilver
#google_analytics: UA-54476418-1

# Pagination
paginate: 5
paginate_path: "page:num"
excerpt_separator: <!--more-->

# Gems
gems:
  - jekyll-archives
  - jekyll-paginate

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title.html

# Archive settings
jekyll-archives:
  enabled: ['tags']
